-- Lab1: Q1
-- Arthur CHANSEL 324265

SELECT PERSONID, NUMBER_OF_CLIPS
FROM (
    SELECT D.PERSONID, COUNT(*) AS NUMBER_OF_CLIPS
    FROM DIRECTOR D, CLIP C
    WHERE D.CLIPID = C.CLIPID
    GROUP BY D.PERSONID
)
WHERE NUMBER_OF_CLIPS = (
    SELECT MAX(NUMBER_OF_CLIPS)
    FROM (
        SELECT COUNT(*) AS NUMBER_OF_CLIPS
        FROM DIRECTOR D, CLIP C
        WHERE D.CLIPID = C.CLIPID
        GROUP BY D.PERSONID
    )
)
;