-- Lab1: Q10
-- Arthur CHANSEL 324265

SELECT C.CLIPID, AVG(CR.VOTES) AS AVERAGE_VOTES
FROM (
    SELECT G.GENRE AS TOP_GENRE, COUNT(*) AS CALCULATION
    FROM CLIP C, GENRE G, CLIPGENRE CG
    WHERE C.CLIPID = CG.CLIPID
        AND G.GENREID = CG.GENREID
    GROUP BY G.GENRE
    ORDER BY CALCULATION DESC
    FETCH FIRST 1 ROWS ONLY
), CLIP C, GENRE G, CLIPGENRE CG, CLIPRATING CR
WHERE C.CLIPID = CG.CLIPID
    AND CG.GENREID = G.GENREID
    AND G.GENRE = TOP_GENRE
    AND C.CLIPID = CR.CLIPID
GROUP BY C.CLIPID
ORDER BY C.CLIPID DESC
FETCH FIRST 10 ROWS ONLY
;