-- Lab1: Q2
-- Arthur CHANSEL 324265

SELECT LANGUAGE
FROM (
    SELECT LANGUAGE
    FROM (
        SELECT L.LANGUAGE, COUNT(*) AS NUMBER_OF_CLIPS
        FROM CLIP C, CLIPLANGUAGE CL, LANGUAGE L
        WHERE C.CLIPID = CL.CLIPID
            AND CL.LANGUAGEID = L.LANGUAGEID
        GROUP BY L.LANGUAGE
    )
    ORDER BY NUMBER_OF_CLIPS DESC
    FETCH FIRST 10 ROWS ONLY
)
ORDER BY LANGUAGE DESC
;