-- Lab1: Q3
-- Arthur CHANSEL 324265

SELECT P.FULLNAME, A.NUMBER_OF_CLIPS AS CALCULATION
FROM PERSON P, (
    SELECT A.PERSONID, COUNT(*) AS NUMBER_OF_CLIPS
    FROM ACTOR A
    GROUP BY A.PERSONID
) A
WHERE P.PERSONID = A.PERSONID
    AND A.NUMBER_OF_CLIPS = (
    SELECT MAX(NUMBER_OF_CLIPS)
    FROM (
        SELECT A.PERSONID, COUNT(*) AS NUMBER_OF_CLIPS
        FROM ACTOR A
        GROUP BY A.PERSONID
    )
)
;