-- Lab1: Q4
-- Arthur CHANSEL 324265

SELECT C.CLIPTITLE, CR.RUNNINGTIMEMINUTES, CR.RUNNINGTIMESECONDS
FROM CLIP C, CLIPRUNNINGTIME CR, COUNTRY CO
WHERE C.CLIPID = CR.CLIPID
    AND CR.RELEASECOUNTRYID = CO.COUNTRYID
    AND CO.COUNTRYNAME = 'France'
ORDER BY CR.RUNNINGTIMEMINUTES DESC, CR.RUNNINGTIMESECONDS DESC
FETCH FIRST 10 ROWS ONLY
;