-- Lab1: Q5
-- Arthur CHANSEL 324265

SELECT CO.COUNTRYNAME, COUNT(*) AS NUMBEROFCLIPS
FROM CLIP C, CLIPCOUNTRY CC, COUNTRY CO
WHERE C.CLIPID = CC.CLIPID
    AND CC.COUNTRYID = CO.COUNTRYID
GROUP BY CO.COUNTRYNAME
ORDER BY CO.COUNTRYNAME DESC
FETCH FIRST 10 ROWS ONLY
;