-- Lab1: Q6
-- Arthur CHANSEL 324265

SELECT G.GENRE, COUNT(*) AS CALCULATION
FROM CLIP C, CLIPCOUNTRY CC, COUNTRY CO, GENRE G, CLIPGENRE CG
WHERE C.CLIPID = CC.CLIPID
    AND CC.COUNTRYID = CO.COUNTRYID
    AND CO.COUNTRYNAME = 'USA'
    AND C.CLIPID = CG.CLIPID
    AND G.GENREID = CG.GENREID
GROUP BY G.GENRE
ORDER BY G.GENRE
FETCH FIRST 10 ROWS ONLY
;