-- Lab1: Q7
-- Arthur CHANSEL 324265

SELECT A.PERSONID, AVG(CR.VOTES) AS AVERAGE_VOTES
FROM ACTOR A, CLIPRATING CR
WHERE A.ACTORROLEID < 4
    AND A.CLIPID = CR.CLIPID
GROUP BY A.PERSONID
ORDER BY A.PERSONID DESC
FETCH FIRST 10 ROWS ONLY
;