-- Lab1: Q8
-- Arthur CHANSEL 324265

SELECT FULLNAME
FROM (
    SELECT FULLNAME, COUNT(*) AS NUMBER_OF_COLLABS
    FROM (
        SELECT W.FULLNAME
        FROM (
            SELECT P.FULLNAME, C.CLIPID
            FROM PERSON P, WRITER W, WRITERROLE WR, CLIP C
            WHERE P.PERSONID = W.PERSONID
                AND W.WRITERROLEID = WR.WRITERROLEID
                AND WR.WORKTYPE = 'screenplay'
                AND W.CLIPID = C.CLIPID
        ) W, (
            SELECT P.FULLNAME, C.CLIPID
            FROM PERSON P, PRODUCER PR, CLIP C
            WHERE P.PERSONID = PR.PERSONID
                AND PR.CLIPID = C.CLIPID
        ) PR
        WHERE W.CLIPID = PR.CLIPID
        GROUP BY W.FULLNAME, PR.FULLNAME
    )
    GROUP BY FULLNAME
)
WHERE NUMBER_OF_COLLABS > 2
ORDER BY FULLNAME DESC
FETCH FIRST 10 ROWS ONLY
;