-- Lab1: Q9
-- Arthur CHANSEL 324265

-- Actors with a Biography without Spouse
SELECT P.FULLNAME, CODIR.NUMBER_OF_CODIRECT AS CALCULATION
FROM (
    SELECT A.PERSONID, COUNT(DISTINCT D.CLIPID) AS NUMBER_OF_CODIRECT
    FROM ACTOR A, PERSON P, DIRECTOR D, DIRECTORROLE DR
    WHERE A.PERSONID = P.PERSONID
        AND P.PERSONID = D.PERSONID
        AND D.DIRECTORROLEID = DR.DIRECTORROLEID
        AND DR.ROLE = 'co-director'
    GROUP BY A.PERSONID
) CODIR, PERSON P, BIOGRAPHY B
WHERE CODIR.NUMBER_OF_CODIRECT > 2
    AND CODIR.PERSONID = P.PERSONID
    and P.PERSONID = B.PERSONID
    AND NOT B.PERSONID = ANY (SELECT S.PERSONID FROM SPOUSES S)
ORDER BY P.FULLNAME DESC
FETCH FIRST 10 ROWS ONLY
;

-- -- Actors except ones that have Biography and Spouse
-- SELECT P.FULLNAME, CODIR.NUMBER_OF_CODIRECT AS CALCULATION
-- FROM (
--     SELECT A.PERSONID, COUNT(DISTINCT D.CLIPID) AS NUMBER_OF_CODIRECT
--     FROM ACTOR A, PERSON P, DIRECTOR D, DIRECTORROLE DR
--     WHERE A.PERSONID = P.PERSONID
--         AND P.PERSONID = D.PERSONID
--         AND D.DIRECTORROLEID = DR.DIRECTORROLEID
--         AND DR.ROLE = 'co-director'
--     GROUP BY A.PERSONID
-- ) CODIR, PERSON P
-- WHERE CODIR.NUMBER_OF_CODIRECT > 2
--     AND CODIR.PERSONID = P.PERSONID
--     AND NOT P.PERSONID = ANY (
--         SELECT P.PERSONID
--         FROM SPOUSES S, BIOGRAPHY B, PERSON P
--         WHERE S.PERSONID = B.PERSONID
--             AND B.PERSONID = P.PERSONID)
-- ORDER BY P.FULLNAME DESC
-- FETCH FIRST 10 ROWS ONLY
-- ;